.libPaths("D:/00 CLOUD/Dropbox/000_statprogs/R/myRlib")
# .libPaths("C:/Users/Mehmet Emin Bay?k/Documents/R/win-library/3.5")
# .libPaths("C:/Program Files/R/R-4.0.4/library")
#
.libPaths()

options("install.lock"=FALSE)

setwd("D:/00 CLOUD/Dropbox/000_statprogs/R")
getwd()


##  .libPaths("D:/stats/phyton")
##  setwd("D:/stats/phyton")


library(akima)
library(aod)
library(boot)
library(brant)
library(car)
library(caret)
library(class)
library(cluster)
library(codetools)
library(compiler)
library(corrplot)
library(DAAG)
library(datasets)
library(dbplyr)
library(DescTools)
library(devtools)
library(digest)
library(dummies)
library(foreign)
library(frailtypack)
library(GGally)
library(ggExtra)
library(ggplot2)
library(generalhoslem)
library(graphics)
library(grDevices)
library(grid)
library(haven)
library(Hmisc)
library(installr)
library(jtools)
library(KernSmooth)
library(latex2exp)
library(lavaan)
library(lattice)
library(learnr)
library(lme4)
library(LMERConvenienceFunctions)
library(lmerTest)
library(lmSupport)
library(lmtest)
library(LogisticDx)
library(markdown)
library(MASS)
library(Matrix)
library(MCMCglmm)
library(mctest)
library(mediation)
library(meta)
library(methods)
library(mgcv)
library(nlme)
library(nnet)
library(OneR)
library(ordinal)
library(parallel)
library(party)
library(peopleanalyticsdata)

library(plyr)
library(dplyr)

library(plotly)
library(QuantPsyc)
library(r2d3)
library(randomForest)
library(rattle)
## library(Rcmdr)
library(RColorBrewer)
library(readr)
library(readxl)
library(relaimpo)
library(rematch)
library(remotes)
library(reprex)
library(reshape2)
library(RLRsim)
library(rmarkdown)
library(rpart)
library(rpart.plot)
## library(Rtools)
library(semPlot)
library(shiny)
library(spatial)
library(splines)
library(stats)
library(stats4)
library(styler)
library(survival)
library(survminer)
library(tcltk)
library(tidyverse)
library(tools)
library(utf8)
library(utils)
library(vcd)
library(yaml)





options("install.lock"=FALSE)

#unlink("D:/00 CLOUD/Dropbox/000_statprogs/R/myRlib/00LOCK", recursive = TRUE)

#install.packages("blob", dependencies = TRUE, INSTALL_opts = '--no-lock')






